/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.22")
    api("org.telegram:telegrambots:6.0.1")
    api("org.slf4j:slf4j-api:2.0.6")
    api("org.slf4j:slf4j-simple:2.0.6")
    api("com.google.code.gson:gson:2.10.1")
    api("org.ton:ton-kotlin:0.2.4")
}

group = "com.mandos"
version = "1.0-SNAPSHOT"
description = "investor-bot"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
